const { contextBridge, ipcRenderer } = require('electron');

// 所有 on* 订阅统一经此注册，并回传退订函数：渲染层若重新初始化，
// 不退订就会叠加监听器，同一条通知被回调多次。
function subscribe(channel, handler) {
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

const api = {
  platform: process.platform,
  setMode: (mode) => ipcRenderer.invoke('window:set-mode', mode),
  beginCollapse: () => ipcRenderer.invoke('window:begin-collapse'),
  setCollapsedHover: (hovering) => ipcRenderer.send('window:set-collapsed-hover', hovering === true),
  setTextInputActive: (active) => ipcRenderer.send('window:set-text-input-active', active === true),
  setTab: (tab) => ipcRenderer.invoke('window:set-tab', tab),
  keepPanelOpen: () => ipcRenderer.send('window:keep-open'),
  ensureMicrophone: () => ipcRenderer.invoke('media:microphone'),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  openPrivacySettings: (pane) => ipcRenderer.invoke('shell:open-privacy-settings', pane),
  searchWeatherCities: (query) => ipcRenderer.invoke('home:weather-search', query),
  getHomeWeather: (location) => ipcRenderer.invoke('home:weather', location),
  getFinanceSettings: () => ipcRenderer.invoke('finance:get-settings'),
  setFinanceProvider: (payload) => ipcRenderer.invoke('finance:set-provider', payload),
  setFinanceRefreshInterval: (seconds) => ipcRenderer.invoke('finance:set-refresh-interval', seconds),
  setFinanceActivity: (payload) => ipcRenderer.invoke('finance:set-activity', payload),
  onFinanceUpdate: (cb) => subscribe('finance:update', (event, payload) => cb(payload)),
  testFinanceProvider: (providerId) => ipcRenderer.invoke('finance:test-provider', providerId),
  refreshFinanceCache: () => ipcRenderer.invoke('finance:refresh'),
  getFinanceOverview: (payload) => ipcRenderer.invoke('finance:overview', payload),
  getFinanceRanking: (payload) => ipcRenderer.invoke('finance:ranking', payload),
  getFinanceQuotes: (payload) => ipcRenderer.invoke('finance:quotes', payload),
  getFinanceHistory: (payload) => ipcRenderer.invoke('finance:history', payload),
  getFinanceFundamentals: (payload) => ipcRenderer.invoke('finance:fundamentals', payload),
  cancelFinanceRequest: (requestId) => ipcRenderer.invoke('finance:cancel', requestId),
  searchFinanceAssets: (query, requestId) => ipcRenderer.invoke('finance:search', { query, requestId }),
  getHomeMusicLibrary: () => ipcRenderer.invoke('home:music-library'),
  setHomeMusicMode: (mode) => ipcRenderer.invoke('home:music-mode', mode),
  selectHomeMusicPlaylist: (payload) => ipcRenderer.invoke('home:music-select-playlist', payload),
  refreshHomeMusicSource: (sourceId) => ipcRenderer.invoke('home:music-refresh-source', sourceId),
  addHomeMusicSource: (payload) => ipcRenderer.invoke('home:music-add-source', payload),
  removeHomeMusicSource: (sourceId) => ipcRenderer.invoke('home:music-remove-source', sourceId),
  browseHomeMusicCategories: (payload) => ipcRenderer.invoke('home:music-browse-categories', payload),
  searchHomeMusicPlaylists: (payload) => ipcRenderer.invoke('home:music-search-playlists', payload),
  browseHomeMusicCategory: (payload) => ipcRenderer.invoke('home:music-browse-category', payload),
  browseHomeMusicRecommend: (payload) => ipcRenderer.invoke('home:music-browse-recommend', payload),
  browseHomeMusicUserPlaylists: (payload) => ipcRenderer.invoke('home:music-browse-user-playlists', payload),
  selectHomeMusicOnlinePlaylist: (payload) => ipcRenderer.invoke('home:music-select-online-playlist', payload),
  chooseHomeMusicFiles: () => ipcRenderer.invoke('home:music-choose-files'),
  chooseHomeMusicFolder: () => ipcRenderer.invoke('home:music-choose-folder'),
  addHomeMusicUrl: (payload) => ipcRenderer.invoke('home:music-add-network', payload),
  removeHomeMusicTrack: (trackId) => ipcRenderer.invoke('home:music-remove', trackId),
  loadHomeMusicTrack: (trackId) => ipcRenderer.invoke('home:music-load', trackId),
  loadHomeMusicCover: (trackId) => ipcRenderer.invoke('home:music-cover', trackId),
  inspectLink: (url) => ipcRenderer.invoke('links:inspect', url),
  listWindows: () => ipcRenderer.invoke('windows:list'),
  focusWindow: (windowId) => ipcRenderer.invoke('windows:focus', windowId),
  saveRecording: (payload) => ipcRenderer.invoke('recordings:save', payload),
  beginAudioCapture: () => ipcRenderer.invoke('captures:audio-begin'),
  endAudioCapture: () => ipcRenderer.invoke('captures:audio-end'),
  openCapture: (mode) => ipcRenderer.invoke('captures:open', mode),
  editCapture: (id) => ipcRenderer.invoke('captures:edit', id),
  stopCapture: () => ipcRenderer.invoke('captures:stop'),
  discardCapture: () => ipcRenderer.invoke('captures:discard'),
  captureState: () => ipcRenderer.invoke('captures:state'),
  listCaptures: () => ipcRenderer.invoke('captures:list'),
  captureSettings: () => ipcRenderer.invoke('captures:settings'),
  saveCaptureSettings: (value) => ipcRenderer.invoke('captures:save-settings', value),
  clearCaptureRegion: () => ipcRenderer.invoke('captures:clear-region'),
  previewCapture: (id) => ipcRenderer.invoke('captures:preview', id),
  renameCapture: (id, title) => ipcRenderer.invoke('captures:rename', { id, title }),
  deleteCapture: (id) => ipcRenderer.invoke('captures:delete', id),
  revealCapture: (id) => ipcRenderer.invoke('captures:reveal', id),
  copyCapture: (id) => ipcRenderer.invoke('captures:copy', id),
  exportCapture: (id) => ipcRenderer.invoke('captures:export', id),
  onCapturesChanged: (cb) => subscribe('captures:changed', (_, state) => cb(state)),
  readRecording: (audioPath) => ipcRenderer.invoke('recordings:read', audioPath),
  deleteRecording: (audioPath) => ipcRenderer.invoke('recordings:delete', audioPath),
  revealRecording: (audioPath) => ipcRenderer.invoke('recordings:reveal', audioPath),
  organizeMaterial: (payload) => ipcRenderer.invoke('smart:organize-material', payload),
  runAI: (payload) => ipcRenderer.invoke('ai:run', payload),
  cancelAI: (requestId) => ipcRenderer.invoke('ai:cancel', requestId),
  testAIProvider: (slot = 'content') => ipcRenderer.invoke('ai:test-provider', { slot }),
  getAIDiagnostics: () => ipcRenderer.invoke('ai:get-diagnostics'),
  clearAIDiagnostics: () => ipcRenderer.invoke('ai:clear-diagnostics'),
  acknowledgeAIMigration: () => ipcRenderer.invoke('ai:ack-migration'),
  onAIEvent: (cb) => subscribe('ai:event', (event, payload) => cb(payload)),
  listCredentials: () => ipcRenderer.invoke('credentials:list'),
  getCredential: (id) => ipcRenderer.invoke('credentials:get', id),
  saveCredential: (payload) => ipcRenderer.invoke('credentials:save', payload),
  deleteCredentials: (ids) => ipcRenderer.invoke('credentials:delete-many', ids),
  copyCredential: (id, field) => ipcRenderer.invoke('credentials:copy', { id, field }),
  getTranscriptionConfig: () => ipcRenderer.invoke('transcription:get-config'),
  setTranscriptionConfig: (config) => ipcRenderer.invoke('transcription:set-config', config),
  startTranscription: () => ipcRenderer.invoke('transcription:start'),
  sendTranscriptionAudio: (bytes) => ipcRenderer.send('transcription:audio', bytes),
  finishTranscription: () => ipcRenderer.invoke('transcription:finish'),
  onTranscriptionEvent: (cb) => subscribe('transcription:event', (event, payload) => cb(payload)),
  listTaskCompletions: () => ipcRenderer.invoke('tasks:recent'),
  scheduleTodoReminders: (items) => ipcRenderer.invoke('todos:schedule-reminders', items),
  notifyPomodoro: (minutes) => ipcRenderer.invoke('pomodoro:notify', minutes),
  onTodoReminder: (cb) => subscribe('todo:reminded', (event, payload) => cb(payload)),
  onEscape: (cb) => subscribe('key:escape', () => cb()),
  onToggleShortcut: (cb) => subscribe('shortcut:toggle-panel', () => cb()),
  onAudioRecordingShortcut: (cb) => subscribe('shortcut:audio-recording', () => cb()),
  onLauncherToggle: (cb) => subscribe('shortcut:toggle-launcher', () => cb()),
  onLauncherClose: (cb) => subscribe('launcher:close', () => cb()),
  launcherSettings: () => ipcRenderer.invoke('launcher:settings'),
  saveLauncherSettings: (settings) => ipcRenderer.invoke('launcher:save-settings', settings),
  finishLauncherFocus: (restore) => ipcRenderer.invoke('launcher:focus', { restore }),
  transferLauncherData: (id, operation) => ipcRenderer.invoke('launcher:extension-data', { id, operation }),
  completeLauncherNavigation: (token, ok) => ipcRenderer.invoke('launcher:navigation-result', { token, ok }),
  launcherIcon: (id) => ipcRenderer.invoke('launcher:icon', { id }),
  queryLauncher: (query, requestId, regexMode = false) => ipcRenderer.invoke('launcher:query', { query, requestId, regexMode }),
  onLauncherPartial: (cb) => subscribe('launcher:partial', (event, payload) => cb(payload)),
  cancelLauncher: () => ipcRenderer.invoke('launcher:cancel'),
  runLauncher: (id, mode = 'default') => ipcRenderer.invoke('launcher:run', { id, mode }),
  openLauncherUrl: (url) => ipcRenderer.invoke('launcher:open-url', { url }),
  listLauncherExtensions: () => ipcRenderer.invoke('launcher:extensions'),
  installLauncherExtension: () => ipcRenderer.invoke('launcher:extension-install'),
  toggleLauncherExtension: (id, enabled) => ipcRenderer.invoke('launcher:extension-toggle', { id, enabled }),
  removeLauncherExtension: (id) => ipcRenderer.invoke('launcher:extension-remove', { id }),
  getHoverSpaceStatus: () => ipcRenderer.invoke('shortcut:hover-space-status'),
  getAppSettings: () => ipcRenderer.invoke('settings:get'),
  setFeature: (featureId, enabled) => ipcRenderer.invoke('settings:set-feature', { featureId, enabled }),
  setDefaultTab: (tab) => ipcRenderer.invoke('settings:set-default-tab', tab),
  setTheme: (theme) => ipcRenderer.invoke('settings:set-theme', theme),
  setNotchHeight: (preference) => ipcRenderer.invoke('settings:set-notch-height', preference),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('settings:set-auto-launch', enabled === true),
  setPanelShortcut: (accelerator) => ipcRenderer.invoke('settings:set-shortcut', { action: 'panel', accelerator }),
  setShortcut: (action, accelerator) => ipcRenderer.invoke('settings:set-shortcut', { action, accelerator }),
  onAppSettingsChanged: (cb) => subscribe('settings:changed', (event, settings) => cb(settings)),
  onRecordShortcut: (cb) => subscribe('app:record-shortcut', () => cb()),
  getWorkspace: () => ipcRenderer.invoke('workspace:get'),
  loadWorkspaceData: () => ipcRenderer.invoke('workspace:load-data'),
  saveWorkspaceData: (storage) => ipcRenderer.invoke('workspace:save-data', storage),
  openWorkspace: () => ipcRenderer.invoke('workspace:open'),
  chooseWorkspace: () => ipcRenderer.invoke('workspace:choose'),
  onWorkspaceChanged: (cb) => subscribe('workspace:changed', (event, info) => cb(info)),
  onCollapseRequest: (cb) => subscribe('window:request-collapse', () => cb()),
  getMetrics: () => ipcRenderer.invoke('window:metrics'),
  onMetricsChanged: (cb) =>
    subscribe('window:metrics-changed', (event, metrics) => cb(metrics)),
  writeClipboard: (entry) => ipcRenderer.invoke('clipboard:write', entry),
  pasteClipboard: (entry) => ipcRenderer.invoke('clipboard:paste', entry),
  readClipImage: (imagePath) => ipcRenderer.invoke('clipboard:readImage', imagePath),
  deleteClipImages: (paths) => ipcRenderer.invoke('clipboard:deleteImages', paths),
  saveNoteImage: (payload) => ipcRenderer.invoke('notes:save-image', payload),
  chooseNoteImages: (noteId) => ipcRenderer.invoke('notes:choose-images', noteId),
  readNoteImage: (imagePath) => ipcRenderer.invoke('notes:read-image', imagePath),
  deleteNoteImages: (noteId) => ipcRenderer.invoke('notes:delete-images', noteId),
  onNewClipEntry: (cb) => subscribe('clipboard:new-entry', (evt, entry) => cb(entry)),
  onOpenClip: (cb) => subscribe('app:open-clip', () => cb()),
  onOpenApiSettings: (cb) => subscribe('app:open-api-settings', () => cb()),
  onTaskNotification: (cb) =>
    subscribe('task-notification:show', (event, notification) => cb(notification)),
  onTaskNotificationQueue: (cb) =>
    subscribe('task-notification:queue', (event, count) => cb(count)),
  onTaskNotificationHide: (cb) =>
    subscribe('task-notification:hide', (event, eventId) => cb(eventId)),
  onTaskCompletion: (cb) =>
    subscribe('task-completion:new', (event, notification) => cb(notification)),
  taskNotificationDismissed: (eventId) =>
    ipcRenderer.send('task-notification:dismissed', eventId),
  activateTaskNotification: (eventId) =>
    ipcRenderer.invoke('task-notification:activate', eventId),
  taskNotificationHover: (paused) =>
    ipcRenderer.send('task-notification:hover', paused === true),
  getSyncStatus: () => ipcRenderer.invoke('sync:get-status'),
  getSyncRuntimeContext: () => ipcRenderer.invoke('sync:get-runtime-context'),
  testSyncConnection: (payload) => ipcRenderer.invoke('sync:test-connection', payload),
  saveSyncBinding: (payload) => ipcRenderer.invoke('sync:save-binding', payload),
  setSyncCategories: (categories) => ipcRenderer.invoke('sync:set-categories', { categories }),
  pauseSync: (paused) => ipcRenderer.invoke('sync:pause', { paused: paused === true }),
  runSyncNow: () => ipcRenderer.invoke('sync:run-now'),
  enqueueSync: (operation) => ipcRenderer.invoke('sync:enqueue', { operation }),
  listSyncConflicts: (payload) => ipcRenderer.invoke('sync:list-conflicts', payload),
  resolveSyncConflict: (payload) => ipcRenderer.invoke('sync:resolve-conflict', payload),
  removeSyncBinding: (payload) => ipcRenderer.invoke('sync:remove-binding', payload),
  cancelSyncTransfer: (transferId) => ipcRenderer.invoke('sync:cancel-transfer', { transferId }),
  uploadSyncObject: (payload) => ipcRenderer.invoke('sync:upload-object', payload),
  downloadSyncObject: (payload) => ipcRenderer.invoke('sync:download-object', payload),
  previewFirstSync: (payload) => ipcRenderer.invoke('sync:first-sync-preview', payload),
  executeFirstSync: (payload) => ipcRenderer.invoke('sync:first-sync-execute', payload),
  cancelFirstSync: (payload) => ipcRenderer.invoke('sync:first-sync-cancel', payload),
  prepareSyncCategoryClear: (payload) => ipcRenderer.invoke('sync:category-clear-preview', payload),
  executeSyncCategoryClear: (payload) => ipcRenderer.invoke('sync:category-clear-execute', payload),
  restoreSyncDeleted: (payload) => ipcRenderer.invoke('sync:restore-deleted', payload),
  onSyncStatus: (cb) => subscribe('sync:status', (event, status) => cb(status)),
  onSyncApplyBatch: (cb) => subscribe('sync:apply-batch', async (event, message) => {
    try {
      const result = await cb(message.batch);
      ipcRenderer.send('sync:projection-result', { requestId: message.requestId, ok: true, result });
    } catch (error) {
      ipcRenderer.send('sync:projection-result', { requestId: message.requestId, ok: false, error: { code: String(error?.code || error?.message || 'renderer_projection_failed').slice(0, 80) } });
    }
  }),
};

// New grouped namespaces are aliases over the stable flat API. Keeping both
// shapes lets existing renderer modules migrate independently without changing IPC.
api.window = Object.freeze({
  setMode: api.setMode,
  beginCollapse: api.beginCollapse,
  setCollapsedHover: api.setCollapsedHover,
  setTextInputActive: api.setTextInputActive,
  setTab: api.setTab,
  keepPanelOpen: api.keepPanelOpen,
  getMetrics: api.getMetrics,
  getHoverSpaceStatus: api.getHoverSpaceStatus,
  onCollapseRequest: api.onCollapseRequest,
  onMetricsChanged: api.onMetricsChanged,
});
api.finance = Object.freeze({
  getSettings: api.getFinanceSettings,
  setProvider: api.setFinanceProvider,
  setRefreshInterval: api.setFinanceRefreshInterval,
  setActivity: api.setFinanceActivity,
  onUpdate: api.onFinanceUpdate,
  testProvider: api.testFinanceProvider,
  refresh: api.refreshFinanceCache,
  overview: api.getFinanceOverview,
  ranking: api.getFinanceRanking,
  quotes: api.getFinanceQuotes,
  history: api.getFinanceHistory,
  fundamentals: api.getFinanceFundamentals,
  cancel: api.cancelFinanceRequest,
  search: api.searchFinanceAssets,
});
api.home = Object.freeze({
  searchWeatherCities: api.searchWeatherCities,
  getWeather: api.getHomeWeather,
  getMusicLibrary: api.getHomeMusicLibrary,
  setMusicMode: api.setHomeMusicMode,
  selectMusicPlaylist: api.selectHomeMusicPlaylist,
  refreshMusicSource: api.refreshHomeMusicSource,
  addMusicSource: api.addHomeMusicSource,
  removeMusicSource: api.removeHomeMusicSource,
  browseMusicCategories: api.browseHomeMusicCategories,
  searchMusicPlaylists: api.searchHomeMusicPlaylists,
  browseMusicCategory: api.browseHomeMusicCategory,
  browseMusicRecommend: api.browseHomeMusicRecommend,
  browseMusicUserPlaylists: api.browseHomeMusicUserPlaylists,
  selectOnlinePlaylist: api.selectHomeMusicOnlinePlaylist,
  chooseMusicFiles: api.chooseHomeMusicFiles,
  chooseMusicFolder: api.chooseHomeMusicFolder,
  addMusicUrl: api.addHomeMusicUrl,
  removeMusicTrack: api.removeHomeMusicTrack,
  loadMusicTrack: api.loadHomeMusicTrack,
  loadMusicCover: api.loadHomeMusicCover,
  organizeMaterial: api.organizeMaterial,
});
api.capture = Object.freeze({
  beginAudio: api.beginAudioCapture,
  endAudio: api.endAudioCapture,
  open: api.openCapture,
  edit: api.editCapture,
  stop: api.stopCapture,
  discard: api.discardCapture,
  state: api.captureState,
  list: api.listCaptures,
  settings: api.captureSettings,
  saveSettings: api.saveCaptureSettings,
  clearRegion: api.clearCaptureRegion,
  preview: api.previewCapture,
  rename: api.renameCapture,
  delete: api.deleteCapture,
  reveal: api.revealCapture,
  copy: api.copyCapture,
  export: api.exportCapture,
  onChanged: api.onCapturesChanged,
});
api.recordings = Object.freeze({
  save: api.saveRecording,
  read: api.readRecording,
  delete: api.deleteRecording,
  reveal: api.revealRecording,
});
api.notes = Object.freeze({
  saveImage: api.saveNoteImage,
  chooseImages: api.chooseNoteImages,
  readImage: api.readNoteImage,
  deleteImages: api.deleteNoteImages,
});
api.launcher = Object.freeze({
  settings: api.launcherSettings,
  saveSettings: api.saveLauncherSettings,
  finishFocus: api.finishLauncherFocus,
  transferData: api.transferLauncherData,
  completeNavigation: api.completeLauncherNavigation,
  icon: api.launcherIcon,
  query: api.queryLauncher,
  onPartial: api.onLauncherPartial,
  cancel: api.cancelLauncher,
  run: api.runLauncher,
  openUrl: api.openLauncherUrl,
  listExtensions: api.listLauncherExtensions,
  installExtension: api.installLauncherExtension,
  toggleExtension: api.toggleLauncherExtension,
  removeExtension: api.removeLauncherExtension,
});
api.settings = Object.freeze({
  get: api.getAppSettings,
  setFeature: api.setFeature,
  setDefaultTab: api.setDefaultTab,
  setTheme: api.setTheme,
  setNotchHeight: api.setNotchHeight,
  setAutoLaunch: api.setAutoLaunch,
  setPanelShortcut: api.setPanelShortcut,
  setShortcut: api.setShortcut,
  onChanged: api.onAppSettingsChanged,
});

api.sync = Object.freeze({
  getStatus: api.getSyncStatus,
  getRuntimeContext: api.getSyncRuntimeContext,
  testConnection: api.testSyncConnection,
  saveBinding: api.saveSyncBinding,
  setCategories: api.setSyncCategories,
  pause: api.pauseSync,
  runNow: api.runSyncNow,
  enqueue: api.enqueueSync,
  listConflicts: api.listSyncConflicts,
  resolveConflict: api.resolveSyncConflict,
  removeBinding: api.removeSyncBinding,
  cancelTransfer: api.cancelSyncTransfer,
  uploadObject: api.uploadSyncObject,
  downloadObject: api.downloadSyncObject,
  previewFirstSync: api.previewFirstSync,
  executeFirstSync: api.executeFirstSync,
  cancelFirstSync: api.cancelFirstSync,
  prepareCategoryClear: api.prepareSyncCategoryClear,
  executeCategoryClear: api.executeSyncCategoryClear,
  restoreDeleted: api.restoreSyncDeleted,
  onStatus: api.onSyncStatus,
  onApplyBatch: api.onSyncApplyBatch,
});

contextBridge.exposeInMainWorld('notchAPI', api);
